services:
  - type: web
    name: wordpress-holberton
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /readme.html
    autoDeploy: true
    disk:
      name: wordpress-data
      mountPath: /var/www/html/wp-content
      sizeGB: 1
    envVars:
      - key: PORT
        value: 10000
      - key: WORDPRESS_DB_HOST
        fromDatabase:
          name: wordpress-db
          property: host
      - key: WORDPRESS_DB_USER
        fromDatabase:
          name: wordpress-db
          property: user
      - key: WORDPRESS_DB_PASSWORD
        fromDatabase:
          name: wordpress-db
          property: password
      - key: WORDPRESS_DB_NAME
        value: wordpress
      - key: WORDPRESS_TABLE_PREFIX
        value: wp_
      - key: WORDPRESS_DEBUG
        value: "false"

databases:
  - name: wordpress-db
    databaseName: wordpress
    user: wordpress
    plan: free
    region: oregon
